services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images
  - docker run -t --entrypoint="/bin/sh" jjmerelo/test-perl6 -c "perl6 --version; which zef "

script:
  - docker run -t -v  /home/travis/build/JJ/p6-wikidata-API:/test jjmerelo/test-perl6

